title.business.name=SMB AGRICOLA HUATUSCO S.A. DE C.V. S.F.C.
label.text.1=Socio
label.text.2=Moneda
label.text.3=Caja
label.text.4=7
label.text.5=SARAHI GUTIERREZ FLORES
label.text.6=INGRESOS POR OTROS CONCEPTOS
label.text.7=VALOR
label.text.8=Firma