title.bussines.name=SMB AGRICOLA BIOCAFE SA DE CV SFC  
title.bussines.office.name=SUCURSAL PARAISO
title.type.operation=OPERACIONES CON BOVEDA
label1=Responsable de boveda
label2=Tipo de transaccion
label3=Hora
label4=Fecha
table.column1=Operacion con
table.column2=Codigo
table.column3=Nombre
label5=Caja
label6=Banco
label7=Sucursal
table2.column1=Denominacion
table2.column2=Numero
table2.column3=Total
label8=Billetes
label9=Monedas
label10=Efectivo
label11=Cheques
label12=Falta
label13=Sobrante
