amortization.header.office=SUCURSAL -
amortization.header.title=TABLA DE AMORTIZACI\u00d3N AL
amortization.description.office.number=Sucursal:
amortization.description.client=Socio :
amortization.description.amount=Monto :
amortization.description.term=Plazo :
amortization.description.product=Producto:
amortization.description.interest=Inter\u00e9s :
amortization.description.wallet=Cartera:
amortization.description.loan.number=Cr\u00e9dito :
amortization.description.date=Fecha :
amortization.description.arrear=Mora :
amortization.description.funding=Financiamiento :
amortization.description.officer=Oficial SF:
amortization.table.installment=CUOTA
amortization.table.duedate=VENCIMIENTO
amortization.table.principal.pending=SALDO CAPITAL
amortization.table.interest=INTER\u00c9S
amortization.table.fee=IVA
amortization.table.principal=CAPITAL
amortization.table.total=CUOTA
amortization.table.date=FECHA
amortization.table.duedays=D.ATR
amortization.table.total=TOTAL
amortization.table.repayment.number=PAGO
amortization.table.repayment.date=FECHA
amortization.table.repayment.principal=CAPITAL
amortization.table.repayment.interest=INTER\u00c9S
amortization.table.repayment.arrear=MORA
amortization.table.repayment.fee=IVA
amortization.table.repayment.amount=PAGO
amortization.table.repayment.office=SUC.PAGO
amortization.table.repayment.transaction=NO.TRANS
amortization.table.repayment.bank=BANCO
amortization.table.repayment.account=CUENTA
amortization.table.repayment.installment=MOV
amortization.total.repayment=TOTAL PAGADO
amortization.principal.paid=SALDO CAPITAL
amortization.duedays=DIAS VENCIDOS
amortization.message=En caso de adelantar o atrasarse en pagos, esta tabla ser\u00e1 invalida para futuros pagos.
amortization.page=P\u00e1gina