label.text.1=Member
label.text.2=Account
label.text.3=Currency
label.text.4=Teller
label.text.5=SAVINGS DEBIT NOTE OTHER CONCEPTS
label.text.6=INTER-BRANCH SAVINGS WITHDRAWAL DEBIT NOTE
label.text.7=Cash
label.text.8=Cheques
label.text.9=Total
label.text.10=Signature
