label.text.1=Socio
label.text.2=Cuenta
label.text.3=Moneda
label.text.4=Caja
label.text.5=NOTA D\u00C9BITO AHORROS OTROS CONCEPTOS
label.text.6=NOTA DE D\u00C9BITO RETIRO AHORRO ENTRE SUCURSALES
label.text.7=Efectivo
label.text.8=Cheques
label.text.9=Total
label.text.10=Firma
