promissory.note.header.title=PAGAR\u00c9
promissory.note.header.business=SUCURSAL:
promissory.note.header.promissory.number=Pagar\u00e9 N\u00b0:
promissory.note.header.date=Fecha:
promissory.note.description.1.1=Debemos y pagaremos incondicionalmente por este pagar\u00e9 a la orden de
promissory.note.description.1.2=, la cantidad de
promissory.note.description.1.3=, misma que deber\u00e1 ser pagada de acuerdo a la siguiente tabla de amortizaci\u00f3n:
promissory.note.amortization.table.duedate=F.Vencimiento
promissory.note.amortization.table.amount=Amortizaci\u00f3n
promissory.note.amortization.table.iva=IVA
promissory.note.amortization.table.interest=Inter\u00e9s Generado
promissory.note.amortization.table.principal=Monto Cuota
promissory.note.amortization.total=PAGO TOTAL:
promissory.note.description.2.1=Pagadero en esta ciudad juntamente con el principal en el domicilio ubicado en AV. 3 PONIENTE ENTRE CALLES 2 Y 4 NO. 414. Por lo que si existe un retraso de los pagos arriba mencionados, la totalidad del saldo insoluto se dar\u00e1 por vencido, generando el vencimiento anticipado de los pagos pendientes, m\u00e1s los intereses moratorios que, en su caso, se generen hasta el pago total del adeudo.\nValor recibido a mi entera satisfacci\u00f3n con anterioridad a la presente fecha siendo la suscripci\u00f3n del presente pagar\u00e9 el recibo m\u00e1s amplio que en derecho proceda por la cantidad antes entregada, para todos los efectos a los que haya lugar. El importe de este pagar\u00e9 causar\u00e1 intereses ordinarios a raz\u00f3n de
promissory.note.description.2.2=mensual, sobre el saldo insoluto del cr\u00e9dito. La cantidad importe de este pagar\u00e9 causar\u00e1 intereses moratorios a raz\u00f3n de
promissory.note.description.2.3=aplicado al saldo insoluto de cada mes o fracci\u00f3n de retraso, mientras dure la mora.
promissory.note.description.3.1=\n\nEste pagar\u00e9 se firma el
promissory.note.description.3.2=, en Huatusco, VERACRUZ DE IGNACIO DE LA LLAVE.
promissory.note.signatures=FIRMAS:
promissory.note.debtor=EL DEUDOR
promissory.note.mister=Sr(a). OBLIGADO PRINCIPAL\n
promissory.note.endorsements=Avales
promissory.note.endorsements.names=Nombres:
promissory.note.endorsements.signatures=Firmas
promissory.note.page=P\u00e1gina