label.text.1=Member
label.text.2=Account
label.text.3=Currency
label.text.4=Cashier
label.text.5=PARTIAL WITHDRAWAL OF SOCIAL CONTRIBUTION
label.text.6=WITHDRAWAL OF SOCIAL CONTRIBUTION
label.text.7=Cash
label.text.8=Checks
label.text.9=Total
label.text.10=Never stop SAVING, savings help you with unexpected expenses such as: Covering health costs, home improvements, education etc.
label.text.11=Signature