label.text.1=Socio
label.text.2=Moneda
label.text.3=Caja
label.text.4=PAGO DE TEL\u00C9FONO
label.text.5=Valor
label.text.6=Comisi\u00F3n (-)
label.text.7=IVA (-)
label.text.8=Total
label.text.9=Contamos con otros servicios que te pueden interesar como: Recargas Telef\u00f3nicas, Remesas Nacionales e Internacionales, Cambio de cheques; \u00a1pregunta a tu cajera!
label.text.10=Firma