label.text.1=Partner
label.text.2=Currency
label.text.3=Teller
label.text.4=PAYMENT OF REMITTANCES
label.text.5=Value
label.text.6=Commission (-)
label.text.7=IVA (-)
label.text.8=Total
label.text.9=Signature