title.business.name=SMB AGRICOLA ABC
title.business.office.name=SAN FRANCISCO
label.text1=Responsable de Bóveda: 
label.value1=SCARLET JOHANSON
label.text2=Tipo de Transacción:
label.value2=IBF CIERRE FINAL DE BOVEDA
label.text3=Operaci\u00f3n con
label.text4=Código
label.text5=Nombre
label.text6=Caja:
label.value6=0
label.text7=Banco:
label.value7=0
label.text8=Sucursal:
label.value8=1
label.text9=Denominación
label.text10=Número
label.text11=Total
label.text12=CHEQUES
label.value12=0
label.value12b=0.00
label.text13=Efectivo + Cheques:
label.text14=Faltante:
label.value14=0.00
label.text15=Sobrante:
label.value15=0.00
label.text19=Entregué Conforme
label.text20=Recibí Conforme
label.text21=Total Efectivo:
