label.text.1=Socio
label.text.2=Moneda
label.text.3=Caja
label.text.4=INGRESO POR OTROS CONCEPTOS
label.text.5=COMISI\u00D3N POR CONSULTA EN BUR\u00D3 DE CR\u00C9DITO
label.text.6=VALOR
label.text.7=Firma
