title=CERTIFICADO DE APORTACI\u00d3N SOCIAL
text.1=SUCURSAL
text.2.1=El presente documento certifica que
text.2.2=, recibi\u00f3 de 
text.2.3=Socio
text.2.4=con el n\u00famero de cuenta
text.2.5=, la cantidad de
text.2.6=. Por el concepto de aportaciones al capital social de la instituci\u00f3n.
text.3.1=Con el monto pagado al capital social de
text.3.2=, el socio adquiere derechos y obligaciones, tal como lo establecen los estatutos de la sociedad. En caso de retiro, el socio podr\u00e1 solicitar el reintegro de este capital al valor que se determine en la asamblea general de socios posterior al cierre del ejercicio fiscal en el que haya solicitado su baja, para lo cual deber\u00e1 sujetarse a los lineamientos que para ello establezca la sociedad en sus reglamentos.
text.4=Gerente de Sucursal:
text.5=Este certificado provisional ser\u00e1 canjeado por el definitivo una vez que la sociedad obtenga la autorizaci\u00f3n de la Comisi\u00f3n Nacional Bancaria y de Valores.