label.text.1=Socio
label.text.2=Cuenta
label.text.3=Moneda
label.text.4=Caja
label.text.5=RETIRO AHORROS NORMAL
label.text.6=Efectivo
label.text.7=Cheques
label.text.8=Total
label.text.9=Nunca dejes de AHORRAR, el ahorro te ayuda para imprevistos como: Solventar gastos de salud, ampliaci\u00F3n de tu casa, educaci\u00F3n etc.
label.text.10=Firma